// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdpy7jCxYrLsCafveMyz8yzQU31NwsdaA',
    appId: '1:42228671981:web:3ae376a48fd71815f9b3e4',
    messagingSenderId: '42228671981',
    projectId: 'fir-773d8',
    authDomain: 'fir-773d8.firebaseapp.com',
    storageBucket: 'fir-773d8.appspot.com',
    measurementId: 'G-BCJVM865MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq2pxw2JwS8SJv1Myls7ZhrEmw9OdyBLU',
    appId: '1:42228671981:android:ba4578a9b2e4750af9b3e4',
    messagingSenderId: '42228671981',
    projectId: 'fir-773d8',
    storageBucket: 'fir-773d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzYpND2OxlEthXaRI41iHgAvoPHk6Aapg',
    appId: '1:42228671981:ios:2d6a289ef8dd04f1f9b3e4',
    messagingSenderId: '42228671981',
    projectId: 'fir-773d8',
    storageBucket: 'fir-773d8.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzYpND2OxlEthXaRI41iHgAvoPHk6Aapg',
    appId: '1:42228671981:ios:2d6a289ef8dd04f1f9b3e4',
    messagingSenderId: '42228671981',
    projectId: 'fir-773d8',
    storageBucket: 'fir-773d8.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdpy7jCxYrLsCafveMyz8yzQU31NwsdaA',
    appId: '1:42228671981:web:fd48a93fcb382d33f9b3e4',
    messagingSenderId: '42228671981',
    projectId: 'fir-773d8',
    authDomain: 'fir-773d8.firebaseapp.com',
    storageBucket: 'fir-773d8.appspot.com',
    measurementId: 'G-R8QV6TKZRF',
  );
}
